package com.quizhub.quizhub.controller;

import com.quizhub.quizhub.dto.*;
import com.quizhub.quizhub.model.Quiz;
import com.quizhub.quizhub.service.FilteredQuizService;
import com.quizhub.quizhub.service.QuizService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/quizzes")
public class QuizController {

    private final QuizService quizService;

    public QuizController(QuizService quizService) {
        this.quizService = quizService;
    }

    @Autowired
    private FilteredQuizService filteredQuizService;

    // Create a new quiz
    @PostMapping("/create")
    public ResponseEntity<Quiz> createQuiz(@RequestBody Quiz quiz) {
        Quiz createdQuiz = quizService.saveQuiz(quiz);
        return new ResponseEntity<>(createdQuiz, HttpStatus.CREATED);
    }

    // Get all quizzes generated by a specific user
    @GetMapping("/{userId}")
    public ResponseEntity<List<Quiz>> getQuizzesByUser(@PathVariable Long userId) {
        List<Quiz> quizzes = quizService.getQuizzesByUser(userId);
        return ResponseEntity.ok(quizzes);
    }

    // Get a specific quiz by its ID and user ID
    @GetMapping("/{id}/user/{userId}")
    public ResponseEntity<Quiz> getQuizByIdAndUser(@PathVariable Long id, @PathVariable Long userId) {
        Optional<Quiz> quizOpt = quizService.getQuizByIdAndUser(id, userId);
        return quizOpt.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // Delete a quiz by its ID
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteQuiz(@PathVariable Long id) {
        quizService.deleteQuiz(id);
        return ResponseEntity.noContent().build();
    }

    /**
     * Endpoint to create a filtered quiz.
     * Expects a JSON payload matching FilteredQuizRequest and a userId as a request parameter.
     *
     * Example request URL:
     * POST /quizzes/filtered?userId=123
     *
     * @param request the filter criteria.
     * @param userId the ID of the user generating the quiz.
     * @return the newly created Quiz entity.
     */
    @PostMapping("/filtered")
    public ResponseEntity<Quiz> createFilteredQuiz(@RequestBody FilteredQuizRequest request,
                                                   @RequestParam Long userId) {
        try {
            Quiz quiz = filteredQuizService.createFilteredQuiz(request, userId);
            return new ResponseEntity<>(quiz, HttpStatus.CREATED);
        } catch (Exception e) {
            // In production, log the error and return a meaningful message.
            return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
        }
    }

    @GetMapping("/all")
    public ResponseEntity<List<BaseQuizDTO>> getAllQuizzes() {
        List<Quiz> quizzes = quizService.getAllQuizzes();
        List<BaseQuizDTO> quizDTOs = quizzes.stream().map(quiz -> {
            switch (quiz.getVisibility()) {
                case FILTERED:
                    return new FilteredQuizDTO(quiz);
                case PUBLIC:
                    return new PublicQuizDTO(quiz);
                case PRIVATE:
                    return new PrivateQuizDTO(quiz);
                default:
                    return new BaseQuizDTO(quiz);
            }
        }).toList();

        return ResponseEntity.ok(quizDTOs);
    }

    @GetMapping("/filtered/{userId}")
    public ResponseEntity<List<FilteredQuizDTO>> getFilteredQuizzesByUser(@PathVariable Long userId) {
        List<Quiz> quizzes = quizService.getFilteredQuizzesByUser(userId);
        List<FilteredQuizDTO> quizDTOs = quizzes.stream()
                .map(FilteredQuizDTO::new)
                .collect(Collectors.toList());
        return ResponseEntity.ok(quizDTOs);
    }


    @GetMapping("/details/{quizId}")
    public ResponseEntity<QuizDTO> getQuizDetails(@PathVariable Long quizId) {
        Optional<QuizDTO> quizOpt = quizService.getQuizDTOById(quizId);
        return quizOpt.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }


}

